version: '2.2'
services:
  php:
    build:
      context: .docker
      dockerfile: php/Dockerfile
    image: '${DOCKER_DEVBOX_REGISTRY}${DOCKER_DEVBOX_REGISTRY_REPOSITORY}/php'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    volumes:
      - '${COMPOSE_PROJECT_DIR}:/var/www/html'
      - '${COMPOSE_PROJECT_DIR}/.docker/php/php-config.ini:/usr/local/etc/php/conf.d/php-config.ini'
      - 'php-composer-cache:/composer/cache'
      - 'php-composer-vendor:/composer/vendor'
    user: '${USER_ID}:${GROUP_ID}'
  web:
    build:
      context: .docker
      dockerfile: web/Dockerfile
    image: '${DOCKER_DEVBOX_REGISTRY}${DOCKER_DEVBOX_REGISTRY_REPOSITORY}/web'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    volumes:
      - '${COMPOSE_PROJECT_DIR}:/var/www/html'
      - '${COMPOSE_PROJECT_DIR}/.docker/web/apache.conf:/usr/local/apache2/conf/custom/apache.conf'
  db:
    build:
      context: .docker
      dockerfile: db/Dockerfile
    image: '${DOCKER_DEVBOX_REGISTRY}${DOCKER_DEVBOX_REGISTRY_REPOSITORY}/db'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    environment:
      - POSTGRES_USER=directus
      - POSTGRES_PASSWORD=directus
    volumes:
      - '${COMPOSE_PROJECT_DIR}:/workdir'
      - 'db-data:/var/lib/postgresql/data'
    user: '${USER_ID}:${GROUP_ID}'
  db2:
    build:
      context: .docker
      dockerfile: db2/Dockerfile
    image: '${DOCKER_DEVBOX_REGISTRY}${DOCKER_DEVBOX_REGISTRY_REPOSITORY}/db2'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    environment:
      - MYSQL_ROOT_PASSWORD=directus
      - MYSQL_DATABASE=directus
      - MYSQL_USER=directus
      - MYSQL_PASSWORD=directus
    volumes:
      - '${COMPOSE_PROJECT_DIR}:/workdir'
      - 'db2-data:/var/lib/mysql'
    user: '${USER_ID}:${GROUP_ID}'
  node:
    build:
      context: .docker
      dockerfile: node/Dockerfile
    image: '${DOCKER_DEVBOX_REGISTRY}${DOCKER_DEVBOX_REGISTRY_REPOSITORY}/node'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    volumes:
      - '${COMPOSE_PROJECT_DIR}:/app'
      - 'node-cache:/home/node/.cache'
      - 'node-npm-packages:/home/node/.npm-packages'
    user: '${USER_ID}:${GROUP_ID}'
volumes:
  php-composer-cache: null
  php-composer-vendor: null
  db-data: null
  db2-data: null
  node-cache: null
  node-npm-packages: null
